markdown: kramdown
permalink: /:year/:i_month/:title
hightlighter: pygments
url: http://blog.thecrescent.top
name: Beyondsky
author: Beyondsky
email: sky_529@live.com
about: "喜欢折腾"
github: beyondskyml

gems: 
 - jekyll-paginate

paginate: 16 # 每页显示的文章列表长度
paginate_path: "page:num"
# safe: true    # 如果使用该选项，则不会加载任何 include 的插件，比如 pagination
# disqus: beyondsky
# beian: 浙ICP备12026616号
# cnzz: 119959
