markdown: kramdown
# permalink: /:year/:i_month/:title
hightlighter: pygments
duoshuo: beyondsky
url: http://besky.me
name: Beyondsky
author: Beyondsky
qq: 1175646849
email: sky_529@live.com
weibo: 2174510607
weibourl: beskyme
about: "学生党，重度选择恐惧症/拖延症，，，喜欢折腾。。。"
github: beyondskyml
safe: true

gems: 
 - jekyll-paginate

paginate: 16 # 每页显示的文章列表长度
# disqus: beyondsky
# paginate_path: "/blog/page:num"
# beian: 浙ICP备12026616号
# cnzz: 119959