markdown: kramdown
permalink: /:year/:i_month/:title
hightlighter: pygments
url: http://besky.me
name: Beyondsky
author: Beyondsky
qq: 1175646849
email: angeTomber@gmail.com
disqus: beyondsky
weibo: 2174510607
github: beyondskyml
safe: true
gems: [jekyll-paginate]
paginate: 16 # 每页显示的文章列表长度
# paginate_path: "/blog/page:num"
about: "学生党，重度选择恐惧症/拖延症，，，喜欢折腾。。。"
#duoshuo: 89ao
#beian: 浙ICP备12026616号
#cnzz: 119959