markdown: rdiscount
permalink: /:year/:month/:title
url: http://beyondsky.tk
name: Beyondsky
author: Beyondsky
qq: 1175646849
email: angeTomber@gmail.com
disqus: beyondsky
weibo: 2174510607
github: beyondskyml
hightlighter: pygments
safe: true
paginate: 20
about: "学生党，重度选择恐惧症/拖延症，，，喜欢折腾。。。"
#duoshuo: 89ao
#beian: 浙ICP备12026616号
#cnzz: 119959
